name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & push the Docker image
        env:
          URL: ${{ secrets.URL }}
          LOCAL_URL: ${{ secrets.LOCAL_URL }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USR: ${{ secrets.DB_USR }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: employee_demo
          IMAGE_TAG: team1-web
        run: |
          docker build --build-arg URL=${URL} --build-arg LOCAL_URL=${LOCAL_URL} --build-arg DB_HOST=${DB_HOST} --build-arg DB_USR=${DB_USR} --build-arg DB_PASS=${DB_PASS}  --build-arg DB_NAME=${DB_NAME} --build-arg JWT_SECRET=${JWT_SECRET} -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
